name: Build Jazz Scales Book

on:
  push:
    branches: ['**']      # run on all branches
    tags: ['v*']          # also run on tags like v1.0.0
  pull_request:
    branches: ['**']
  workflow_dispatch: {}

permissions:
  contents: write         # required to create a Release & upload assets

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install system deps (LilyPond)
        run: |
          sudo apt-get update
          sudo apt-get install -y lilypond zip

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install abjad==3.25.0 matplotlib pypdf reportlab

      # ➕ Add --midi to actually render MIDI as well as PDF
      - name: Generate all keys (LY, PDF & MIDI)
        run: |
          python scripts/jazz_scales_abjad_keys.py \
            --step 5 --count 12 --start C --prefer auto --anchor nearest --mode major \
            --pdf --midi --bpm 96

      # ➕ Collect .midi/.mid into out/
      - name: Stage outputs
        run: |
          mkdir -p out
          mv jazz_scales_abjad_*.ly out/ || true
          mv jazz_scales_abjad_*.pdf out/ || true
          mv jazz_scales_abjad_*.midi out/ 2>/dev/null || true
          mv jazz_scales_abjad_*.mid  out/ 2>/dev/null || true
          python scripts/make_cover.py
          python scripts/make_book_keys.py

      # ➕ Include MIDI files in the single ZIP
      - name: Package single download (ZIP)
        run: |
          cd out
          zip -r jazz-scales-all-keys.zip \
            jazz_scales_abjad_*.pdf \
            jazz_scales_abjad_*.midi \
            jazz_scales_abjad_*.mid \
            cover.pdf toc.pdf Jazz-Scales-Book.pdf

      # Only publish a Release on tag builds
      - name: Create GitHub Release & upload assets
        if: ${{ github.ref_type == 'tag' }}
        uses: softprops/action-gh-release@v2
        with:
          files: |
            out/jazz-scales-all-keys.zip
            out/Jazz-Scales-Book.pdf
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Optional: CI artifacts on non-tag runs (remove if you don't want them)
      - name: Upload CI artifacts (non-release runs)
        if: ${{ github.ref_type != 'tag' }}
        uses: actions/upload-artifact@v4
        with:
          name: jazz-scales-ci
          path: |
            out/jazz-scales-all-keys.zip
            out/Jazz-Scales-Book.pdf
